---
- name: Deploy resolv.conf template
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    
- name: Update {{ ansible_distribution }} hosts
  yum:
    update_cache: true
    update_only: true

- name: Install packages
  package:
    name: "{{ item }}"
  with_items: "{{ packages[ansible_distribution][ansible_distribution_major_version] }}"

- name: Install ipa-server master
  shell: >
    ipa-server-install {{ freeipa_server_common_params | trim }} {{ freeipa_server_master_params | trim }}
  args:
    creates: "{{ freeipa_server_sysrestore_file }}"
  notify: restart ipa service  