---
- name: Converge
  hosts: all
  tasks:
    - name: "Include base_setup"
      include_role:
        name: "base_setup"
    - name: "Include freeipa_server"
      include_role:
        name: "freeipa_server"
